### ISSUE TITLE
Link to documentation has invalid github.com SSL certificate

### ISSUE THREAD

**Issue by thavlik** [notriddle/rust-leaky-cow#1]
This link is presenting with a GitHub.com SSL certificate that has a name mismatch. Screenshot is attached.

<img width="736" alt="screen shot 2019-02-09 at 2 41 27 pm" src="https://user-images.githubusercontent.com/740031/52526070-123a8200-2c79-11e9-9c9c-dc0a4fb96030.png">

Mac OS X, Safari 12.0.2

**Comment by notriddle** [comment]
Removed it. Just use https://docs.rs/leaky-cow
